# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20170216_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderTreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_root', models.BooleanField(default=False)),
                ('is_leaf', models.BooleanField(default=True)),
                ('checked', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='report.FolderTreeNode')),
            ],
        ),
    ]
